bot:
  prefix: []
rate_limits:
  max_attempts: 5
  window_seconds: 1800  # 30 min
organization:
  name: "TEST Squadron - Best Squardon!" 

channels:
  verification_channel_id: 1313551608491282543  # Replace with your verification channel ID

roles:
  bot_verified_role_id: 1313551309869416528     # Replace with your BotVerified role ID
  main_role_id: 1313551051076665394            # Replace with your Main role ID
  affiliate_role_id: 1313551109373165671       # Replace with your Affiliate role ID
  non_member_role_id: 1313551221625192458      # Replace with your Non-Member role ID
  bot_admins:
    - "246604397155581954"

  lead_moderators:
    - "1174838659065847859"

selectable_roles:
- 1313551051076665394 #Main
- 1313551109373165671 #Affiliate
- 1313551221625192458 #Non-Member
- 1313551309869416528 #BotVerified

logging:
  level: "INFO"  # Set to "DEBUG", "INFO", "WARNING", "ERROR", or "CRITICAL"

voice:
  cooldown_seconds: 5  # Cooldown period in seconds
  expiry_days: 30  # Expiry period for voice channel data in days


database:
  path: "TESTDatabase.db"