bot:
  prefix: "!"
rate_limits:
  max_attempts: 3
  window_seconds: 10800  # 3 hours
organization:
  name: "TEST Squadron - Best Squardon!"

embeds:
  verification:
    title: "📡 Account Verification"
    description: |
      Welcome! To get started, please **click the 'Get Token' button below**.

      After obtaining your token, verify your RSI / Star Citizen account by using the provided buttons.

      If you don't have an account, feel free to [enlist here](https://robertsspaceindustries.com/enlist?referral=STAR-MXL7-VM6G).
    color: "0xFFBB00"
    thumbnail_url: "https://robertsspaceindustries.com/static/images/logo.png"
  token:
    title: "📡 Account Verification"
    description: |
      Use the **4-digit PIN** below for verification.

      **Instructions:**
      :one: Login to your [RSI account profile](https://robertsspaceindustries.com/account/profile).
      :two: Add the PIN to your **Short Bio** field.
      :three: Scroll down and click **Apply All Changes**.
      :four: Return here and click the 'Verify' button below.

      :information_source: *Note: The PIN expires <t:{expires_unix}:R>.*
    color: "0x00FF00"
    thumbnail_url: "https://robertsspaceindustries.com/static/images/logo.png"
    field_name: "🔑 Your Verification PIN"
  error:
    title: "❌ Verification Failed"
    color: "0xFF0000"
  success:
    title: "🎉 Verification Successful!"
    color: "0x00FF00"
  cooldown:
    title: "⏰ Cooldown Active"
    description: |
      You have reached the maximum number of verification attempts.
      Please try again <t:{wait_until}:R>.
    color: "0xFFA500"
